#!perl

# NO_PERINCI_CMDLINE_SCRIPT
# FRAGMENT id=shcompgen-hint command=_cpanm

# DATE
# VERSION

use strict;
use warnings;
use File::Which;

my $lcpanm_path = which("lcpanm") or die "Can't find lcpanm in PATH\n";

$ENV{LCPANM_PERL5OPT} = join(
    " ",
    "-MModule::Load::In::INIT=-ignore_load_error,App::cpanminus::script::Patch::RunShcompgen=-load_target;0;-warn_target_loaded;0",
    "-MModule::Load::In::INIT=-ignore_load_error,App::cpanminus::script::Patch::UseURIFromFoundMirror=-load_target;0;-warn_target_loaded;0",
    (defined $ENV{LCPANM_PERL5OPT} ? ($ENV{LCPANM_PERL5OPT}) : ()),
);

my @cmd = (
    $lcpanm_path,
    @ARGV,
);

print "lcpanm-perlancar: LCPANM_PERL5OPT='$ENV{LCPANM_PERL5OPT}' exec: ".join(" ", @cmd), "\n" if $ENV{DEBUG};
exec @cmd;

# ABSTRACT: Install modules from local CPAN (PERLANCAR's flavor)
# PODNAME:

=head1 SYNOPSIS

Use like you would use L<lcpanm>:

 % lcpanm-perlancar -n Some::Module ...

To alias it as C<lcpanm> in your shell, e.g. in bash:

 alias lcpanm=lcpanm-perlancar


=head1 DESCRIPTION

L<lcpanm-perlancar> is a wrapper over L<lcpanm>. It runs lcpanm patched with
some patches (see the source for more details).


=head1 SEE ALSO

L<lcpanm>

L<cpanm>
